package pl.ceveme.application.database;

import java.util.HashMap;
import java.util.Map;

public class CityMapping {

    public static final Map<String, String> CITY_MAPPING = new HashMap<>();

        static {
            CITY_MAPPING.put("wwa", "Warszawa");
            CITY_MAPPING.put("warsaw", "Warszawa");
            CITY_MAPPING.put("warszawie", "Warszawa");
            CITY_MAPPING.put("warszawa (centrum)", "Warszawa");
            CITY_MAPPING.put("warsaw, mazowieckie, poland", "Warszawa");
            CITY_MAPPING.put("warszawie poszukujemy", "Warszawa");
            CITY_MAPPING.put("kyiv and warsaw", "Warszawa");
            CITY_MAPPING.put("warsaw remote", "Warszawa");
            CITY_MAPPING.put("warsaw hybrid", "Warszawa");
            CITY_MAPPING.put("warsaw hybrd", "Warszawa");
            CITY_MAPPING.put("warsaw -hybrid", "Warszawa");

            CITY_MAPPING.put("cracow", "Kraków");
            CITY_MAPPING.put("krakowie", "Kraków");
            CITY_MAPPING.put("krakow", "Kraków");
            CITY_MAPPING.put("region kraków", "Kraków");
            CITY_MAPPING.put("krakowie lub warszawie", "Kraków");
            CITY_MAPPING.put("kraków and gdańsk", "Kraków");
            CITY_MAPPING.put("kraków and london", "Kraków");
            CITY_MAPPING.put("cracow or gdansk", "Kraków");

            CITY_MAPPING.put("wroclaw", "Wrocław");
            CITY_MAPPING.put("wro", "Wrocław");
            CITY_MAPPING.put("breslau", "Wrocław");

            CITY_MAPPING.put("poznan", "Poznań");
            CITY_MAPPING.put("ponzań", "Poznań");

            CITY_MAPPING.put("gdansk", "Gdańsk");
            CITY_MAPPING.put("gdańsku", "Gdańsk");
            CITY_MAPPING.put("gdańsk.", "Gdańsk");
            CITY_MAPPING.put("rejonie w gdańsku", "Gdańsk");
            CITY_MAPPING.put("trójmiasto", "Gdańsk");

            CITY_MAPPING.put("lodz", "Łódź");
            CITY_MAPPING.put("łodzi", "Łódź");
            CITY_MAPPING.put("oddział inpost łódź", "Łódź");
            CITY_MAPPING.put("politechnika łódzka", "Łódź");

            CITY_MAPPING.put("szczecin", "Szczecin");
            CITY_MAPPING.put("bydgoszcz", "Bydgoszcz");
            CITY_MAPPING.put("lublin", "Lublin");
            CITY_MAPPING.put("katowice.", "Katowice");
            CITY_MAPPING.put("śląskie", "Katowice");
            CITY_MAPPING.put("silesia", "Katowice");

            CITY_MAPPING.put("rzeszow", "Rzeszów");
            CITY_MAPPING.put("torun", "Toruń");
            CITY_MAPPING.put("bialystok", "Białystok");
            CITY_MAPPING.put("czestochowa", "Częstochowa");
            CITY_MAPPING.put("zielona gora", "Zielona Góra");

            CITY_MAPPING.put("bielany wrocławskie", "Bielany Wrocławskie");
            CITY_MAPPING.put("nowy dwór mazowiecki.", "Nowy Dwór Mazowiecki");
            CITY_MAPPING.put("ostrówek węgrowski", "Ostrówek");
            CITY_MAPPING.put("stare bojanowo", "Stare Bojanowo");
            CITY_MAPPING.put("tarnowo podgórne", "Tarnowo Podgórne");
            CITY_MAPPING.put("głogów małopolski", "Głogów Małopolski");
            CITY_MAPPING.put("starogard gdański", "Starogard Gdański");
            CITY_MAPPING.put("grodzisk mazowiecki", "Grodzisk Mazowiecki");
            CITY_MAPPING.put("gorzów wielkopolski", "Gorzów Wielkopolski");
            CITY_MAPPING.put("konstantynów łódzki", "Konstantynów Łódzki");
            CITY_MAPPING.put("piotrków trybunalski", "Piotrków Trybunalski");
            CITY_MAPPING.put("tomaszów mazowiecki", "Tomaszów Mazowiecki");
            CITY_MAPPING.put("kędzierzyn-koźle", "Kędzierzyn-Koźle");
            CITY_MAPPING.put("jelcz-laskowice", "Jelcz-Laskowice");
            CITY_MAPPING.put("czechowice-dziedzice", "Czechowice-Dziedzice");
            CITY_MAPPING.put("ruda śląska", "Ruda Śląska");
            CITY_MAPPING.put("siemianowice śląskie", "Siemianowice Śląskie");
            CITY_MAPPING.put("piekary śląskie", "Piekary Śląskie");
            CITY_MAPPING.put("dąbrowa górnicza", "Dąbrowa Górnicza");
            CITY_MAPPING.put("środa wielkopolska", "Środa Wielkopolska");
            CITY_MAPPING.put("środa śląska", "Środa Śląska");
            CITY_MAPPING.put("ostrów wielkopolski", "Ostrów Wielkopolski");
            CITY_MAPPING.put("ostrów mazowiecka", "Ostrów Mazowiecka");
            CITY_MAPPING.put("mińsk mazowiecki", "Mińsk Mazowiecki");
            CITY_MAPPING.put("aleksandrów łódzki", "Aleksandrów Łódzki");
            CITY_MAPPING.put("solec kujawski", "Solec Kujawski");
            CITY_MAPPING.put("kostrzyn nad odrą", "Kostrzyn nad Odrą");
            CITY_MAPPING.put("konstancin-jeziorna", "Konstancin-Jeziorna");
            CITY_MAPPING.put("kamień", "Kamień");
            CITY_MAPPING.put("lidzbark warmiński", "Lidzbark Warmiński");
            CITY_MAPPING.put("biała podlaska", "Biała Podlaska");
            CITY_MAPPING.put("nowa sól", "Nowa Sól");
            CITY_MAPPING.put("nowy targ", "Nowy Targ");
            CITY_MAPPING.put("nowy sącz", "Nowy Sącz");
            CITY_MAPPING.put("stalowa wola", "Stalowa Wola");
            CITY_MAPPING.put("zduńska wola", "Zduńska Wola");
            CITY_MAPPING.put("jastrzębie-zdrój", "Jastrzębie-Zdrój");
            CITY_MAPPING.put("krosno.", "Krosno");
            CITY_MAPPING.put("ustka.", "Ustka");
            CITY_MAPPING.put("świnoujście", "Świnoujście");


            CITY_MAPPING.put("kyiv", "Kijów");
            CITY_MAPPING.put("kiev", "Kijów");
            CITY_MAPPING.put("lviv", "Lwów");
            CITY_MAPPING.put("l'viv", "Lwów");
            CITY_MAPPING.put("london", "Londyn");
            CITY_MAPPING.put("londyn", "Londyn");
            CITY_MAPPING.put("new york", "Nowy Jork");
            CITY_MAPPING.put("munich", "Monachium");
            CITY_MAPPING.put("muenchen", "Monachium");
            CITY_MAPPING.put("berlin", "Berlin");
            CITY_MAPPING.put("frankfurt nad menem", "Frankfurt nad Menem");
            CITY_MAPPING.put("stuttgart", "Stuttgart");
            CITY_MAPPING.put("essen", "Essen");
            CITY_MAPPING.put("offenburg", "Offenburg");
            CITY_MAPPING.put("celle", "Celle");
            CITY_MAPPING.put("vienna", "Wiedeń");
            CITY_MAPPING.put("prague", "Praga");
            CITY_MAPPING.put("brussels", "Bruksela");
            CITY_MAPPING.put("brussels and oostende", "Bruksela");
            CITY_MAPPING.put("amsterdam", "Amsterdam");
            CITY_MAPPING.put("rotterdam", "Rotterdam");
            CITY_MAPPING.put("the hague", "Haga");
            CITY_MAPPING.put("the hague, netherlands", "Haga");
            CITY_MAPPING.put("kerkrade", "Kerkrade");
            CITY_MAPPING.put("copenhagen", "Kopenhaga");
            CITY_MAPPING.put("stockholm", "Sztokholm");
            CITY_MAPPING.put("helsinki", "Helsinki");
            CITY_MAPPING.put("tallinn", "Tallinn");
            CITY_MAPPING.put("riga", "Ryga");
            CITY_MAPPING.put("vilnius", "Wilno");
            CITY_MAPPING.put("sofia", "Sofia");
            CITY_MAPPING.put("bucharest", "Bukareszt");
            CITY_MAPPING.put("bucharest-hybrid", "Bukareszt");
            CITY_MAPPING.put("budapest", "Budapeszt");
            CITY_MAPPING.put("bratislava", "Bratysława");
            CITY_MAPPING.put("belgrade", "Belgrad");
            CITY_MAPPING.put("zagreb", "Zagrzeb");
            CITY_MAPPING.put("madrid", "Madryt");
            CITY_MAPPING.put("barcelona", "Barcelona");
            CITY_MAPPING.put("malaga", "Malaga");
            CITY_MAPPING.put("valetta", "Valetta");
            CITY_MAPPING.put("st. julian’s", "St. Julian's");
            CITY_MAPPING.put("lisbon", "Lizbona");
            CITY_MAPPING.put("porto", "Porto");
            CITY_MAPPING.put("dublin", "Dublin");
            CITY_MAPPING.put("zurich", "Zurych");
            CITY_MAPPING.put("zürich", "Zurych");
            CITY_MAPPING.put("athens", "Ateny");
            CITY_MAPPING.put("dubai", "Dubaj");
            CITY_MAPPING.put("rijad", "Rijad");
            CITY_MAPPING.put("yerevan", "Erywań");
            CITY_MAPPING.put("tbilisi", "Tbilisi");
            CITY_MAPPING.put("shenzhen", "Shenzhen");
            CITY_MAPPING.put("hong kong", "Hongkong");
            CITY_MAPPING.put("san jose", "San Jose");
            CITY_MAPPING.put("los angeles", "Los Angeles");
            CITY_MAPPING.put("newcastle", "Newcastle");
            CITY_MAPPING.put("pittsburgh", "Pittsburgh");
            CITY_MAPPING.put("minneapolis", "Minneapolis");
            CITY_MAPPING.put("mineapolis", "Minneapolis");
            CITY_MAPPING.put("brisbane", "Brisbane");
            CITY_MAPPING.put("karvina", "Karwina");
            CITY_MAPPING.put("karviná, czechy", "Karwina");
            CITY_MAPPING.put("luxembourg", "Luksemburg");
            CITY_MAPPING.put("luksemburg", "Luksemburg");


            CITY_MAPPING.put("remote", "Zdalnie");
            CITY_MAPPING.put("remote/hybrid", "Zdalnie");
            CITY_MAPPING.put("zdalnie", "Zdalnie");
            CITY_MAPPING.put("cała", "Polska");
            CITY_MAPPING.put("polska", "Polska");
            CITY_MAPPING.put("poland", "Polska");
            CITY_MAPPING.put("poland (remote)", "Zdalnie");
            CITY_MAPPING.put("poland (remote", "Zdalnie");
            CITY_MAPPING.put("polsce", "Polska");
            CITY_MAPPING.put("na miejscu", "Stacjonarnie");


            CITY_MAPPING.put("germany", "Niemcy");
            CITY_MAPPING.put("niemcy", "Niemcy");
            CITY_MAPPING.put("uk", "Wielka Brytania");
            CITY_MAPPING.put("anglii", "Wielka Brytania");
            CITY_MAPPING.put("united kingdom", "Wielka Brytania");
            CITY_MAPPING.put("usa", "USA");
            CITY_MAPPING.put("stany zjednoczone", "USA");
            CITY_MAPPING.put("stanach zjednoczonych", "USA");
            CITY_MAPPING.put("switzerland", "Szwajcaria");
            CITY_MAPPING.put("szwajcaria", "Szwajcaria");
            CITY_MAPPING.put("norwegii w", "Norwegia");
            CITY_MAPPING.put("sweden in", "Szwecja");
            CITY_MAPPING.put("denmark in", "Dania");
            CITY_MAPPING.put("estonia", "Estonia");
            CITY_MAPPING.put("romania", "Rumunia");
            CITY_MAPPING.put("serbia", "Serbia");
            CITY_MAPPING.put("spain or", "Hiszpania");
            CITY_MAPPING.put("hiszpanii", "Hiszpania");
            CITY_MAPPING.put("saudi arabia", "Arabia Saudyjska");
            CITY_MAPPING.put("malta", "Malta");
            CITY_MAPPING.put("austria", "Austria");


            CITY_MAPPING.put("july", null);
            CITY_MAPPING.put("june", null);
            CITY_MAPPING.put("march", null);
            CITY_MAPPING.put("december", null);
            CITY_MAPPING.put("october", null);
            CITY_MAPPING.put("days", null);
            CITY_MAPPING.put("person assessment days", null);

            CITY_MAPPING.put("sales", null);
            CITY_MAPPING.put("finance", null);
            CITY_MAPPING.put("marketing", null);
            CITY_MAPPING.put("accounting", null);
            CITY_MAPPING.put("controlling", null);
            CITY_MAPPING.put("engineering", null);
            CITY_MAPPING.put("economics", null);
            CITY_MAPPING.put("healthcare", null);
            CITY_MAPPING.put("it services", null);
            CITY_MAPPING.put("it security", null);
            CITY_MAPPING.put("it studiesmin.", null);
            CITY_MAPPING.put("computer science", null);
            CITY_MAPPING.put("business administration", null);
            CITY_MAPPING.put("electrical engineering", null);
            CITY_MAPPING.put("medical nutrition", null);
            CITY_MAPPING.put("customs", null);
            CITY_MAPPING.put("payroll", null);
            CITY_MAPPING.put("logistics", null);
            CITY_MAPPING.put("traffic", null);
            CITY_MAPPING.put("grid", null);
            CITY_MAPPING.put("test", null);
            CITY_MAPPING.put("java", null);
            CITY_MAPPING.put("javascript and angular", null);
            CITY_MAPPING.put("symfony", null);
            CITY_MAPPING.put("elixir", null);
            CITY_MAPPING.put("figma", null);
            CITY_MAPPING.put("sap s", null);
            CITY_MAPPING.put("sap and non", null);
            CITY_MAPPING.put("linux-based embedded systems", null);
            CITY_MAPPING.put("ibm mdm development", null);
            CITY_MAPPING.put("large language models", null);
            CITY_MAPPING.put("chatgpt", null);
            CITY_MAPPING.put("vs code", null);
            CITY_MAPPING.put("mso", null);
            CITY_MAPPING.put("excelu", null);
            CITY_MAPPING.put("confluencecollaborated with cross", null);
            CITY_MAPPING.put("agile", null);
            CITY_MAPPING.put("agile ceremonies", null);
            CITY_MAPPING.put("scrum", null);
            CITY_MAPPING.put("this role", null);
            CITY_MAPPING.put("this role if", null);
            CITY_MAPPING.put("role", null);
            CITY_MAPPING.put("senior", null);
            CITY_MAPPING.put("contract", null);
            CITY_MAPPING.put("umowa o prac", null); // Ucięte
            CITY_MAPPING.put("naszym zespole", null);
            CITY_MAPPING.put("zespole technology risk", null);
            CITY_MAPPING.put("zakresie rozwoju", null);
            CITY_MAPPING.put("zakres obowiązków", null);
            CITY_MAPPING.put("wystawianie i kompletowanie", null);
            CITY_MAPPING.put("sprzedaż usługi", null);
            CITY_MAPPING.put("prowadzenie systemu zarządzania", null);
            CITY_MAPPING.put("konfiguracja techniczna aplikacji", null);
            CITY_MAPPING.put("księgowości poszukuje starszej", null);
            CITY_MAPPING.put("księgowości poszukuje młodszej", null);
            CITY_MAPPING.put("krakow. you", null);
            CITY_MAPPING.put("the technology stack", null);
            CITY_MAPPING.put("dane kandydata", null);
            CITY_MAPPING.put("digitalchoice of benefits", null);
            CITY_MAPPING.put("influencer marketing", null);
            CITY_MAPPING.put("it z projektami", null);
            CITY_MAPPING.put("mainframe z", null);
            CITY_MAPPING.put("central", null);
            CITY_MAPPING.put("central and eastern", null);
            CITY_MAPPING.put("cee region", null);
            CITY_MAPPING.put("europe", null);
            CITY_MAPPING.put("european", null);
            CITY_MAPPING.put("europie centralnej", null);
            CITY_MAPPING.put("english", null);
            CITY_MAPPING.put("german", null);
            CITY_MAPPING.put("neu", null);

            CITY_MAPPING.put("pwc", null);
            CITY_MAPPING.put("pwc liczy ponad", null);
            CITY_MAPPING.put("pwc to ponad", null);
            CITY_MAPPING.put("polsce. posiada", null);
            CITY_MAPPING.put("polsce. posiada ponad", null);
            CITY_MAPPING.put("polsce. ba", null);
            CITY_MAPPING.put("polsce z blisko", null);
            CITY_MAPPING.put("polsce grupę egis", null);
            CITY_MAPPING.put("polsce havi dysponuje", null);
            CITY_MAPPING.put("polsce od", null);
            CITY_MAPPING.put("jti cenimy różnorodno", null);
            CITY_MAPPING.put("bosch kształtujemy przyszło", null);
            CITY_MAPPING.put("sieć badawcza łukasiewicz", null);
            CITY_MAPPING.put("olx pracujemy razem", null);
            CITY_MAPPING.put("surf inc. wierzymy", null);
            CITY_MAPPING.put("immersion łączymy vr", null);
            CITY_MAPPING.put("taxcelerate to wyjątkowy", null);
            CITY_MAPPING.put("foundever", null);
            CITY_MAPPING.put("henkel", null);
            CITY_MAPPING.put("forbes", null);
            CITY_MAPPING.put("ey-parthenon i", null);
            CITY_MAPPING.put("epam", null);
            CITY_MAPPING.put("kuehne", null);
            CITY_MAPPING.put("smith", null);
            CITY_MAPPING.put("marketo", null);
            CITY_MAPPING.put("bny", null);
            CITY_MAPPING.put("ecs", null);
            CITY_MAPPING.put("mso", null);
            CITY_MAPPING.put("yetiz", null);
            CITY_MAPPING.put("cundall", null);
            CITY_MAPPING.put("columbus one", null);
            CITY_MAPPING.put("kuchnia vikinga", null);
            CITY_MAPPING.put("electric llc", null);
            CITY_MAPPING.put("siemens plc programming", null);
            CITY_MAPPING.put("galerii dominikańskiej", "Wrocław");
            CITY_MAPPING.put("laboratorium zbożowym", null);
            CITY_MAPPING.put("na stanowisku pracy", null);
            CITY_MAPPING.put("dziale personalnym", null);
            CITY_MAPPING.put("organizacji", null);
            CITY_MAPPING.put("pracy", null);
            CITY_MAPPING.put("br", null);
            CITY_MAPPING.put("cze", null);
        }

}
